#!/usr/bin/env bash

FILE_PATH="experiments/01_gplvm_curveID_L.py"
NUM_INDUCING=10
MAX_ITER=10
LOG_FREQ=1

python $FILE_PATH 1 1 $NUM_INDUCING $MAX_ITER $LOG_FREQ
python $FILE_PATH 1 2 $NUM_INDUCING $MAX_ITER $LOG_FREQ
python $FILE_PATH 2 1 $NUM_INDUCING $MAX_ITER $LOG_FREQ
python $FILE_PATH 2 2 $NUM_INDUCING $MAX_ITER $LOG_FREQ
python $FILE_PATH all 1 $NUM_INDUCING $MAX_ITER $LOG_FREQ
python $FILE_PATH all 2 $NUM_INDUCING $MAX_ITER $LOG_FREQ